var level4_chapter2 = [
["They crashed because they had ..... burst tyre", "a", "an", "the", "___", ],
["Would you mind turning off ...... lights when you leave?", "the", "a", "an", "___", ],
["The party was so loud that she asked them to turn ...... music down", "the", "a", "an", "___", ],
["They live in ...... lovely flat", "a", "an", "the", "___", ],
["Their offices are on ....... fifth floor", "the", "a", "an", "___", ],
["We start ...... work at a quarter to nine", "___", "a", "an", "the", ],
["The only sport I enjoy is ...... rugby", "___", "a", "an", "the", ],
["It's ...... old house and needs some work", "an", "a", "the", "___", ],
["I left it at ...... office", "the", "a", "an", "___", ],
["Could you take ....... books you borrowed back to the library, please?", "the", "a", "an", "___", ],
["Come in- ...... water's lovely and warm", "the", "a", "an", "___", ],
["He joined .... union when he started work", "a", "an", "the", "___", ],
["It's in ....... Milton Road", "___", "a", "an", "the", ],
["It's ...... second road on the right", "the", "a", "an", "___", ],
["He's wearing ..... blue suit", "a", "an", "the", "___", ],
["He's wearing ...... tie I gave him", "the", "a", "an", "___", ],
["What time would you like ...... breakfast?", "___", "a", "an", "the", ],
["I don't know anywhere in ...... world quite as beautiful as here", "the", "a", "an", "___", ],
["We were stopped by ...... police last night", "the", "a", "an", "___", ],
["She's been looking for ...... job since she was made redundant", "a", "an", "the", "___", ],
];
