var level4_chapter1 = [
["Ice cream is __ to frozen yogurt. " ,"comparable " ,"compareable " ,"comparible" ,"None" ],
["Sharks __ almost anything. " ,"consume" ,"consumme " ,"cunsume " ,"None" ],
["A __ is also called a dresser. " ,"bureau " ,"burauo " ,"burreau" ,"None" ],
["A __ ride would be fun. " ,"gondola" ,"gondohla " ,"gondela " ,"None" ],
["He played in a ___. " ,"concert " ,"consert " ,"conscert" ,"None" ],
["The government __ is upset again. " ,"faction " ,"facktion " ,"facsion" ,"None" ],
["The __ of the wedding was well-done. " ,"coordination " ,"cordination " ,"coordinasion" ,"None" ],
["The __ sank in the lake. " ,"catamaran" ,"catemaran " ,"catmaren " ,"None" ],
["I need to __ inches to centimeters. " ,"convert " ,"cunvert " ,"converte" ,"None" ],
["The trash will __ in 100 years. " ,"decompose" ,"decompost " ,"decumpose " ,"None" ],
["A diamond is a hard __ . " ,"substance " ,"substanse " ,"substence" ,"None" ],
["She's a __ for the high school. " ,"benefactor" ,"benefacter " ,"benfactor " ,"None" ],
["An __ is a shy person. " ,"introvert " ,"intrevert " ,"intruvret" ,"None" ],
["Don't __ your little brother by the ankles! " ,"suspend" ,"susspend " ,"saspend " ,"None" ],
["A __ fell off her dress. " ,"sequin" ,"sequen " ,"secquin " ,"None" ],
["It's time to __ with the others. " ,"rendezvous " ,"rendezvou " ,"rondevous" ,"None" ],
["Jack will __ in the race. " ,"compete " ,"compeate " ,"compeet" ,"None" ],
["Don't try to __ the law. " ,"circumvent" ,"circumvend " ,"circkumvent " ,"None" ],
["It's __ to the post office. " ,"adjacent " ,"ajacent " ,"adjascent" ,"None" ],
["Don't __ this last question. " ,"omit" ,"ommit " ,"omitt " ,"None" ],
];
