var level1_chapter3 = [
["Is your brother ..... home?" ,"at" ,"in" ,"on" ,"into" ],
["There is no unity ..... the leaders." ,"among" ,"between" ,"to" ,"with" ],
["He is a man ..... humble origin" ,"of" ,"off" ,"with" ,"for" ],
["The village is 5 miles ..... the highway" ,"off" ,"of" ,"for" ,"by" ],
["He is ..... to Mumbai" ,"off" ,"in" ,"on" ,"over" ],
["The boy was beaten ..... a stick" ,"with" ,"by" ,"at" ,"over" ],
["He discussed the problem ..... his parents" ,"with" ,"by" ,"at" ,"off" ],
["John was punished ..... his father" ,"by" ,"with" ,"in" ,"against" ],
["Can you finish the work ..... tomorrow?" ,"by" ,"for" ,"from" ,"since" ],
["He has been absent ..... last week" ,"since" ,"for" ,"from" ,"over" ],
["I think we should apologize ..... him" ,"to" ,"with" ,"over" ,"at" ],
["Do you believe ..... life after death?" ,"in" ,"on" ,"to" ,"at" ],
["When did you arrive ..... France?" ,"in" ,"at" ,"on" ,"to" ],
["When did your interest ..... philosophy begin?" ,"in" ,"at" ,"on" ,"to" ],
["We had a long discussion ..... politics" ,"about" ,"on" ,"in" ,"over" ],
["We might go camping, it depends ..... the weather" ,"on" ,"in" ,"at" ,"over" ],
["My father never showed if he was disappointed ..... me" ,"with" ,"by" ,"at" ,"to" ],
];
