var level1_chapter2 = [
["...... apple a day keeps the doctor away", "an", "a", "the", "___", ],
["Are you looking for ....... shampoo? ", "the", "a", "an", "___", ],
["I checked ....... mailbox again. ", "the", "a", "an", "___", ],
["Can I have ....... spoon please? ", "a", "an", "the", "___", ],
["I was born into ....... poor family. ", "a", "an", "the", "___", ],
["She will come back in ....... hour. ", "an", "a", "the", "___", ],
["Have you been to ....... Space Needle Tower in Seattle? ", "the", "a", "an", "___", ],
["I would love to talk to one of ....... managers. ", "the", "a", "an", "___", ],
["What ....... amazing view! ", "an", "a", "the", "___", ],
["The helicopter landed on ....... roof of a building.", "the", "a", "an", "___", ],
["Mount Everest is in ....... Himalayas", "the", "a", "an", "___", ],
["....... President of the United States was elected last year", "the", "a", "an", "___", ],
["We spent a lot of time swimming in ...... sea on holiday", "the", "a", "an", "___", ],
["London is on ...... River Thames", "the", "a", "an", "___", ],
["She did ..... MA in French literature", "an", "a", "the", "___", ],
["My garden's looking lovely now that ...... daffodils are in flower", "the", "a", "an", "___", ],
["It's ...... most expensive hotel in town", "the", "a", "an", "___", ],
["....... Mount Everest is in the Himalayas", "___", "a", "an", "the", ],
["My mother is allergic to ........ cigarette smoke", "___", "a", "an", "the", ],
["An atheist does not believe in ....... God", "___", "a", "an", "the", ],
];
