var level5_chapter2 = [
["The River Nile is .... longest river of all", "the", "a", "an", "___", ],
["I was really angry because I missed ...... bus", "the", "a", "an", "___", ],
["Christmas Day falls on ...... Sunday this year", "a", "an", "the", "___", ],
["There were no buses so I had to take .... taxi", "a", "an", "the", "___", ],
["He fell in love with ....... girl next door.", "the", "a", "an", "___", ],
["Thanks for ....... help.", "the", "a", "an", "___", ],
["You are ....... good teacher.", "a", "an", "the", "___", ],
["Give me another half ....... hour.", "an", "a", "the", "___", ],
["Could you help me pick ....... university?", "a", "an", "the", "___", ],
["....... door is still open. Please close it fully.", "the", "a", "an", "___", ],
["....... American Revolution took place in the 19th century.", "the", "a", "an", "___", ],
["He has ....... old car.", "an", "a", "the", "___", ],
["He doesn't mind sleeping on ....... floor.", "the", "a", "an", "___", ],
["This is ....... interesting problem.", "an", "a", "the", "___", ],
["I have ....... question to ask you.", "a", "an", "the", "___", ],
["He is ....... policeman.", "a", "an", "the", "___", ],
["I am ....... citizen of Portugal.", "a", "an", "the", "___", ],
["Charles has bought ....... new yacht.", "a", "an", "the", "___", ],
["Who is ....... guy she's talking with?", "the", "a", "an", "___", ],
["Do you remember ....... movie we watched together?", "the", "a", "an", "___", ],
];
