var level5_chapter1 = [
["They formed a __ bond. " ,"cohesive " ,"coheesive " ,"coheassive" ,"None" ],
["His __ is bothering him. " ,"conscience" ,"consciensce " ,"concience " ,"None" ],
["Jason received a __ for his behavior. " ,"suspension " ,"susspension " ,"suspention" ,"None" ],
["Don't __ the animals. " ,"provoke" ,"provouk " ,"pravoke " ,"None" ],
["He made a ___ in science class. " ,"pendulum " ,"penduluum " ,"pendjulum" ,"None" ],
["He used a towel to __ the water. " ,"absorb " ,"abbsorb " ,"abzorb" ,"None" ],
["Use your power of __ to win people over. " ,"persuasion " ,"persusion " ,"persuazion" ,"None" ],
["The __ man was arrested. " ,"disruptive" ,"dissruptive " ,"disrupteve " ,"None" ],
["Her __ was remarkable. " ,"bravery " ,"bravry " ,"braverey" ,"None" ],
["That is a __ tablecloth. " ,"gingham" ,"ginghum " ,"gingum " ,"None" ],
["A person with lots of new ideas is called a __ . " ,"Liberal " ,"Liberel " ,"Liberral" ,"None" ],
["The airplane is ready for __. " ,"descent" ,"dessent " ,"decent " ,"None" ],
["The __ event is being planned. " ,"impending " ,"inpending " ,"imppending" ,"None" ],
["The __ destroyed the administration. " ,"dissent" ,"disent " ,"discent " ,"None" ],
["They wanted to __ the team mascot. " ,"abduct" ,"abduckt " ,"obduct " ,"None" ],
["The __ might win the case. " ,"defendant " ,"defendent " ,"deffendant" ,"None" ],
["Jack felt __ when he lost. " ,"dejected " ,"dejeckted " ,"dejectid" ,"None" ],
["We all must __ with each other. " ,"coexist" ,"coexits " ,"coeexist " ,"None" ],
["The __ of computers was revolutionary. " ,"advent " ,"advint " ,"addvent" ,"None" ],
["This question is ___. " ,"mandatory" ,"mandetory " ,"manndatory " ,"None" ],
];
