var level3_chapter3 = [
["Alcohol33", "Ethyl alcohol", "Sodium bicarbonate", "Potassium aluminum sulfate dodecahydrate", "Aluminum oxide(Al2O3)"],
["Alka Seltzer33", "Sodium bicarbonate", "Ethyl alcohol", "Potassium aluminum sulfate dodecahydrate", "Aluminum oxide(Al2O3)"],
["Alum33", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol", "Aluminum oxide(Al2O3)"],
["Alumina33", "Aluminum oxide(Al2O3)", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol"],
["Alundum3", "Fused alumina", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol"],
["Alcohol3", "Ethyl alcohol", "Sodium bicarbonate", "Potassium aluminum sulfate dodecahydrate", "Aluminum oxide(Al2O3)"],
["Alka Seltzer3", "Sodium bicarbonate", "Ethyl alcohol", "Potassium aluminum sulfate dodecahydrate", "Aluminum oxide(Al2O3)"],
["Alum3", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol", "Aluminum oxide(Al2O3)"],
["Alumina3", "Aluminum oxide(Al2O3)", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol"],
["Alundum3", "Fused alumina", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol"],
["Alcohol3", "Ethyl alcohol", "Sodium bicarbonate", "Potassium aluminum sulfate dodecahydrate", "Aluminum oxide(Al2O3)"],
["Alka Seltzer3", "Sodium bicarbonate", "Ethyl alcohol", "Potassium aluminum sulfate dodecahydrate", "Aluminum oxide(Al2O3)"],
["Alum3", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol", "Aluminum oxide(Al2O3)"],
["Alumina3", "Aluminum oxide(Al2O3)", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol"],
["Alundum3", "Fused alumina", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol"],
["Alcohol3", "Ethyl alcohol", "Sodium bicarbonate", "Potassium aluminum sulfate dodecahydrate", "Aluminum oxide(Al2O3)"],
["Alka Seltzer3", "Sodium bicarbonate", "Ethyl alcohol", "Potassium aluminum sulfate dodecahydrate", "Aluminum oxide(Al2O3)"],
["Alum3", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol", "Aluminum oxide(Al2O3)"],
["Alumina3", "Aluminum oxide(Al2O3)", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol"],
["Alundum3", "Fused alumina", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol"]
];
