var level3_chapter2 = [
["Alcohol32", "Ethyl alcohol", "Sodium bicarbonate", "Potassium aluminum sulfate dodecahydrate", "Aluminum oxide(Al2O3)"],
["Alka Seltzer32", "Sodium bicarbonate", "Ethyl alcohol", "Potassium aluminum sulfate dodecahydrate", "Aluminum oxide(Al2O3)"],
["Alum32", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol", "Aluminum oxide(Al2O3)"],
["Alumina4", "Aluminum oxide(Al2O3)", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol"],
["Alundum5", "Fused alumina", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol"],
["Alcohol1", "Ethyl alcohol", "Sodium bicarbonate", "Potassium aluminum sulfate dodecahydrate", "Aluminum oxide(Al2O3)"],
["Alka Seltzer2", "Sodium bicarbonate", "Ethyl alcohol", "Potassium aluminum sulfate dodecahydrate", "Aluminum oxide(Al2O3)"],
["Alum3", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol", "Aluminum oxide(Al2O3)"],
["Alumina4", "Aluminum oxide(Al2O3)", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol"],
["Alundum5", "Fused alumina", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol"],
["Alcohol1", "Ethyl alcohol", "Sodium bicarbonate", "Potassium aluminum sulfate dodecahydrate", "Aluminum oxide(Al2O3)"],
["Alka Seltzer2", "Sodium bicarbonate", "Ethyl alcohol", "Potassium aluminum sulfate dodecahydrate", "Aluminum oxide(Al2O3)"],
["Alum3", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol", "Aluminum oxide(Al2O3)"],
["Alumina4", "Aluminum oxide(Al2O3)", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol"],
["Alundum5", "Fused alumina", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol"],
["Alcohol1", "Ethyl alcohol", "Sodium bicarbonate", "Potassium aluminum sulfate dodecahydrate", "Aluminum oxide(Al2O3)"],
["Alka Seltzer2", "Sodium bicarbonate", "Ethyl alcohol", "Potassium aluminum sulfate dodecahydrate", "Aluminum oxide(Al2O3)"],
["Alum3", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol", "Aluminum oxide(Al2O3)"],
["Alumina4", "Aluminum oxide(Al2O3)", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol"],
["Alundum5", "Fused alumina", "Potassium aluminum sulfate dodecahydrate", "Sodium bicarbonate", "Ethyl alcohol"]
];
