var level1_chapter1  = [
["Nick works on an __ committee. " ,"advisory " ,"advizory " ,"advisery" ,"None", ],
["She's got an __ friend. " ,"imaginary" ,"imaginery " ,"imagenary " ,"None" ],
["They need to meet the __. " ,"objective " ,"obgecttive " ,"abjective" ,"None" ],
["We must __ to environmental conditions. " ,"adapt" ,"adopt " ,"adabt " ,"None" ],
["She needs to run some___. " ,"errands " ,"errans " ,"erands" ,"None" ],
["The __ experiment is finished. " ,"laboratory " ,"labratory " ,"labertory" ,"None" ],
["The factory __ was increased 20%. " ,"productivity " ,"producitivity " ,"productivety" ,"None" ],
["He got an __ at the doctor's office. " ,"injection" ,"injectien " ,"injectshun " ,"None" ],
["You are making __ progress. " ,"continual " ,"continnual " ,"continueal" ,"None" ],
["That company uses heavy __. " ,"machinery" ,"mashinery " ,"machinnery " ,"None" ],
["I need some __. " ,"advice " ,"advices " ,"advise" ,"None" ],
["Ducks are __ birds. " ,"migratory" ,"migratorry " ,"migaratory " ,"None" ],
["What is the __ of the story? " ,"moral " ,"morrale " ,"morale" ,"None" ],
["It's an ___ mission. " ,"exploratory" ,"exploretory " ,"exploritory " ,"None" ],
["We went to a __. " ,"funeral" ,"funaral " ,"funerol " ,"None" ],
["They want to __ a baby. " ,"adopt " ,"adoppt " ,"adopped" ,"None" ],
["There was a volcano __ in Hawaii. " ,"eruption " ,"erupsion " ,"erruption" ,"None" ],
["A kidnapping is also called an__. " ,"abduction" ,"abducktion " ,"abbduction " ,"None" ],
["You need to see a __. " ,"specialist " ,"specialest " ,"specalist" ,"None" ],
["Her __ was lifted by the news. " ,"morale" ,"morrale " ,"moral " ,"None" ],
];
